version: 0.1
phases:
install:
commands:
- npm install
pre_build:
commands:
- echo This is pre_build
build:
commands:
- npm run build
post_build:
commands:
- echo Build completed on `date`
- aws s3 cp build s3://cloudchefweb.com/ --recursive